spring:
  shell:
    interactive:
      enabled: true
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/weather_data?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: weatheradmin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 8080
logging:
  level:
    org.springframework: DEBUG