spring:
  shell:
    interactive:
      enabled: true
  main:
    banner-mode: off
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/weather_data
    username: postgres
    password: toor
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 8080
logging:
  level:
    org.springframework: DEBUG